apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jx4-poi-map-app-dev
  annotations:
    argocd/app-name: jx4-poi-map-app-dev
    backstage.io/kubernetes-id: jx4-poi-map-app
    backstage.io/kubernetes-namespace: jx4
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rosa916-rvhvd/jx4-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa916.9nln.p1.openshiftapps.com/dev-pipelines/ns/jx4/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa916.9nln.p1.openshiftapps.com/k8s/ns/jx4/deployments/jx4-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa916.9nln.p1.openshiftapps.com/#https://github.com/rosa916-rvhvd/jx4-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://jx4-poi-map-app-jx4.apps.rosa916.9nln.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/joshix"
  system: workshop-system-jx4
  consumesApis:
    - gateway-api-jx4
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-jx4
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/joshix"
